---
- hosts: virtual_machines
  gather_facts: true

  tasks:
    - name: Whoami
      ansible.builtin.command: whoami
      register: whoami

    - name: Display whoami
      debug:
        var: whoami.stdout

    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - git
          - zsh
        state: present
        update_cache: yes
      become: true

    - name: Display the operating system of the remote host
      debug:
        var: ansible_facts['os_family']

    - name: Display only the architecture of the remote host
      debug:
        var: ansible_facts['architecture']

    - name: Ensure qemu-system-arm is installed if architecture is aarch64
      ansible.builtin.apt:
        name: qemu-system-arm
        state: present
      become: true
      when: ansible_facts['architecture'] == 'aarch64'

    - name: Ensure qemu-system-x86 is installed if architecture is x86_64
      ansible.builtin.apt:
        name: qemu-system-x86
        state: present
      become: true
      when: ansible_facts['architecture'] == 'x86_64'

    - name: Ensure libvirtd/qemu and vm management packages are installed
      ansible.builtin.apt:
        name:
          - libvirt-daemon-driver-qemu
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virtinst
          - libosinfo-bin
          - virt-manager
        state: present
        update_cache: yes
      become: true

    - name: Ensure the libvirtd service is available
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Ensure virt-lightning and its requirements are installed
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - pkg-config
          - gcc
          - libvirt-dev
          - python3-dev
        state: present
        update_cache: yes
      become: true

    - name: Ensure pipx is installed for Python package isolation
      ansible.builtin.pip:
        name: pipx
        executable: pip3

    - name: Ensure pipx bin directory is in the PATH for bash
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:~/.local/bin'
        create: yes
        state: present
        regexp: '^export PATH=.*~/.local/bin.*$'
      become: false
      when: ansible_env.SUDO_USER is defined or ansible_env.USER is defined

    - name: Ensure pipx bin directory is in the PATH for zsh
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'export PATH=$PATH:~/.local/bin'
        create: yes
        state: present
        regexp: '^export PATH=.*~/.local/bin.*$'
      become: false
      when: ansible_env.SUDO_USER is defined or ansible_env.USER is defined

    - name: Ensure pipx path is in .bashrc
      ansible.builtin.shell: grep -q '~/.local/bin' ~/.bashrc
      register: bashrc_check
      failed_when: false
      changed_when: false

    - name: Ensure pipx path is in .zshrc
      ansible.builtin.shell: grep -q '~/.local/bin' ~/.zshrc
      register: zshrc_check
      failed_when: false
      changed_when: false

    - name: Ensure pipx is initialized (pipx ensurepath)
      ansible.builtin.shell: pipx ensurepath
      become: false
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.local/bin"
      when: bashrc_check.rc != 0 or zshrc_check.rc != 0

    - name: Make pipx_list to search for virt-lightning
      ansible.builtin.command: pipx list
      register: pipx_list
      changed_when: false

    - name: Ensure virt-lightning is installed using pipx
      ansible.builtin.shell: pipx install virt-lightning
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.local/bin"
      when: "'virt-lightning' not in pipx_list.stdout"

    - name: Ensure virt-lightning directories exist
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0775'
      loop:
        - { path: /var/lib/virt-lightning }
        - { path: /var/lib/virt-lightning/pool }
        - { path: /var/lib/virt-lightning/pool/upstream }
      become: true

    - name: Set ownership for /var/lib/virt-lightning/pool
      ansible.builtin.file:
        path: /var/lib/virt-lightning/pool
        state: directory
        owner: libvirt-qemu
        group: kvm
        recurse: yes
      become: true

    - name: Set ownership for /var/lib/virt-lightning/pool/upstream
      ansible.builtin.file:
        path: /var/lib/virt-lightning/pool/upstream
        state: directory
        owner: tool
        group: tool
        recurse: yes
      become: true

    - name: Link ~/.local/bin/vl to /usr/local/bin/vl
      ansible.builtin.file:
        src: "~/.local/bin/vl"
        dest: "/usr/local/bin/vl"
        state: link
        force: yes
      become: true

    - name: Make list of distros available with virt-lightning
      ansible.builtin.shell: 'vl distro_list'
      register: vl_distro_list

    - name: Ensure the executing user is a member of management groups
      ansible.builtin.user:
        name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        groups:
          - libvirt
          - kvm
        append: yes
      register: user_added_to_groups
      become: true
      when: ansible_env.SUDO_USER is defined or ansible_env.USER is defined

    - name: Display all IPv4 addresses
      debug:
        var: ansible_facts['all_ipv4_addresses']

    - name: Display the vl distro list
      debug:
        var: vl_distro_list.stdout

    - name: Reboot the server to apply group changes
      ansible.builtin.reboot:
      become: false
      when: user_added_to_groups.changed
